// frontend/src/content/components/button/examples/small.svelte
<script>
  import { Button, ButtonGroup } from "@i-dot-ai-npm/component-library-svelte";
</script>

<ButtonGroup>
  <Button type="button" tertiary small>Edit</Button>
  <Button type="button" tertiary small>Export</Button>
  <Button type="button" tertiary small>Download</Button>
  <Button type="button" small>Save</Button>
</ButtonGroup>

// frontend/src/content/components/button/examples/small.react.tsx
import { Button, ButtonGroup } from "@i-dot-ai-npm/component-library-react";

export default function Example() {
  return (
    <ButtonGroup>
      <Button tertiary type="button" small>Edit</Button>
      <Button tertiary type="button" small>Export</Button>
      <Button tertiary type="button" small>Download</Button>
      <Button type="button" small>Save</Button>
    </ButtonGroup>
  );
}
