// frontend/src/content/components/button/examples/tertiary.svelte
<script>
  import { Button, ButtonGroup } from "@i-dot-ai-npm/component-library-svelte";
</script>

<ButtonGroup>
    <Button type="button" tertiary>Action 1</Button>
    <Button type="button" tertiary>Action 2</Button>
    <Button type="button" tertiary>Action 3</Button>
    <Button type="button" tertiary>Action 4</Button>
    <Button type="button" tertiary>Action 5</Button>
</ButtonGroup>

// frontend/src/content/components/button/examples/tertiary.solid.tsx
import { Button, ButtonGroup } from "@i-dot-ai-npm/component-library-solid";

export default function Example() {
  return (
    <ButtonGroup>
        <Button type="button" tertiary>Action 1</Button>
        <Button type="button" tertiary>Action 2</Button>
        <Button type="button" tertiary>Action 3</Button>
        <Button type="button" tertiary>Action 4</Button>
        <Button type="button" tertiary>Action 5</Button>
    </ButtonGroup>
  );
}
